config:
  name:
    Passport::Android::AuthSdk::Feature
  build_counter:
    MobileAuthLibrary_MobileLoginSdkAndroid_Deploy
  runner_version:
    2020.08.26-7257842
stages:
  lib:
    work_dir:
      .
    cmd:
      - ./gradlew check build --info --stacktrace
    lxc:
      2525562503
    android-sdk:
      platforms(28,29,30,31)+tools(31.0.0)
    artifacts:
      +lib/build/outputs/*: lib/outputs
      +sample/build/reports/*: sample/reports
    multislot:
      LARGE